/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppApprovalsRouteImport } from './routes/app.approvals'
import { Route as AppAuditRouteImport } from './routes/app.audit'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDuplicatesRouteImport } from './routes/app.duplicates'
import { Route as AppExceptionsRouteImport } from './routes/app.exceptions'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppLedgerRouteImport } from './routes/app.ledger'
import { Route as AppPurchaseOrdersRouteImport } from './routes/app.purchase-orders'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppVendorsRouteImport } from './routes/app.vendors'
import { Route as AppVerificationRouteImport } from './routes/app.verification'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDuplicatesRoute = AppDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AppRoute,
} as any)
const AppExceptionsRoute = AppExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgerRoute = AppLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersRoute = AppPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppVerificationRoute = AppVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/duplicates': typeof AppDuplicatesRoute
  '/app/exceptions': typeof AppExceptionsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/verification': typeof AppVerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/duplicates': typeof AppDuplicatesRoute
  '/app/exceptions': typeof AppExceptionsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/verification': typeof AppVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/approvals': typeof AppApprovalsRoute
  '/app/audit': typeof AppAuditRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/duplicates': typeof AppDuplicatesRoute
  '/app/exceptions': typeof AppExceptionsRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/ledger': typeof AppLedgerRoute
  '/app/purchase-orders': typeof AppPurchaseOrdersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/verification': typeof AppVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/approvals'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/duplicates'
    | '/app/exceptions'
    | '/app/invoices'
    | '/app/ledger'
    | '/app/purchase-orders'
    | '/app/settings'
    | '/app/vendors'
    | '/app/verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/approvals'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/duplicates'
    | '/app/exceptions'
    | '/app/invoices'
    | '/app/ledger'
    | '/app/purchase-orders'
    | '/app/settings'
    | '/app/vendors'
    | '/app/verification'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/approvals'
    | '/app/audit'
    | '/app/dashboard'
    | '/app/duplicates'
    | '/app/exceptions'
    | '/app/invoices'
    | '/app/ledger'
    | '/app/purchase-orders'
    | '/app/settings'
    | '/app/vendors'
    | '/app/verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/approvals': {
      id: '/app/approvals'
      path: '/approvals'
      fullPath: '/app/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/duplicates': {
      id: '/app/duplicates'
      path: '/duplicates'
      fullPath: '/app/duplicates'
      preLoaderRoute: typeof AppDuplicatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/exceptions': {
      id: '/app/exceptions'
      path: '/exceptions'
      fullPath: '/app/exceptions'
      preLoaderRoute: typeof AppExceptionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ledger': {
      id: '/app/ledger'
      path: '/ledger'
      fullPath: '/app/ledger'
      preLoaderRoute: typeof AppLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/purchase-orders': {
      id: '/app/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/app/purchase-orders'
      preLoaderRoute: typeof AppPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors': {
      id: '/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/verification': {
      id: '/app/verification'
      path: '/verification'
      fullPath: '/app/verification'
      preLoaderRoute: typeof AppVerificationRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppAuditRoute: typeof AppAuditRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDuplicatesRoute: typeof AppDuplicatesRoute
  AppExceptionsRoute: typeof AppExceptionsRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppLedgerRoute: typeof AppLedgerRoute
  AppPurchaseOrdersRoute: typeof AppPurchaseOrdersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppVerificationRoute: typeof AppVerificationRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApprovalsRoute: AppApprovalsRoute,
  AppAuditRoute: AppAuditRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDuplicatesRoute: AppDuplicatesRoute,
  AppExceptionsRoute: AppExceptionsRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppLedgerRoute: AppLedgerRoute,
  AppPurchaseOrdersRoute: AppPurchaseOrdersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppVerificationRoute: AppVerificationRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
